[package]
name = "knn_test_binary"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
linear_algebra = { path = "../../Documents/The Vault/Programming Notes/Rust/a_rusty_knn/linear_algebra" }